#!/bin/bash

set -e
cd "$(dirname "$0")/highlightjs"

cp ../objectivescript.js src/languages/objectivescript.js
mkdir test/detect/objectivescript
touch test/detect/objectivescript/default.txt

npm install
node tools/build.js objectivescript

rm src/languages/objectivescript.js
rm -rf test/detect/objectivescript

cp build/highlight.pack.js ../Pod/Assets/Highlighter/highlight.min.js
